### ISSUE TITLE
no available backends for storage class cvs-standard  

### ISSUE THREAD

**Issue by arunkumarjca** [okrause/GKE-Trident-CVS#2]
Hi Team,

I have tried with same backend json and storage class yaml but im getting error ,

PVC  LOGS

Type     Reason                Age                From                                                                                     Message
  ----     ------                ----               ----                                                                                     -------
  Normal   Provisioning          14s (x5 over 27s)  csi.trident.netapp.io_trident-csi-XXXXXX  External provisioner is provisioning volume for claim "default/nfs-pvc"
  Normal   ProvisioningFailed    14s (x5 over 27s)  csi.trident.netapp.io                                                                    no available backends for storage class cvs-standard
  Warning  ProvisioningFailed    14s (x5 over 27s)  csi.trident.netapp.io_trident-csi-XXXXXX  failed to provision volume with StorageClass "cvs-standard": rpc error: code = Unknown desc = no available backends for storage class cvs-standard
  Normal   ExternalProvisioning  12s (x3 over 27s)  persistentvolume-controller                                                              waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator

**Comment by okrause** [comment]
Trident cannot find suitable backends. Likely you missed a step in the "Configure Trident" part or the recipe. Maybe forgot to set a variable before creating the backend.

Here is how you can inspect the existing backends. tridentctl get backend -o json 
https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/backends.html#viewing-the-existing-backends

If you missed variables, you will find some of the json values missing. Look for inconsistencies. If you cannot find any backend, repeat the "Configure Trident" procedure carefully.

**Comment by arunkumarjca** [comment]
Hi Oliver,

Thanks for your reply .

Using this  tridentctl get backend -o json i could see the Backend in the output 

 "storage": {
        "gcpcvs_XXXX_pool": {
          "name": "gcpcvs_XXXX_pool",
          "storageAttributes": {
            "backendType": {
              "offer": [
                "gcp-cvs"

I observed that if add the backend the in Storage class then i can able to create the PVC .but if i give only selector i couldn't  able to create PVC .. 

Sorry i couldnt get what variable im missing but i have add below variable part of backend 

1.storage Driver 
2.Project number
3.PRoject ID
4.network
5.api key
6.nfsMountOptions
7.storage

Kindly let me let me if miss any thing here 
Thanks for your valuable time .

I Could see below output for this command  ./tridentctl get backend -n trident -o json | jq '[.items[] | {backend: .name, storageClasses: [.storage[].

storageClasses]|unique}]'

storageClasses]|unique}]'
[
  {
    "backend": "gcpcvs_XXX",
    "storageClasses": [
      []
    ]
  }
]

**Comment by okrause** [comment]
Hi,

sorry for the late reply, didn't get an notification that you responded. The output you sent doesn't really help me to understand the issue.

My recommendation:
Trident needs a backend. My recipe creates a backend which the storage classes will use. Basically, the recipe helps you fill out the variables in the template at https://github.com/okrause/GKE-Trident-CVS/blob/master/backend-cvs-gcp-advanced-template.json

Have a look. Github marks the variables red for me. Basically, substitute these variables with data from your environment. This should give you a valid backend file. Then create a new backend with this file using tridentctl. You may have to delete the old backend before. Here is an example how a valid backend file should look like [GCP backend](https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/backend-gcp-cvs-virtual-pools.json).

**Comment by arunkumarjca** [comment]
Hi Oliver,

Sorry i too missed you comments .

I have retried and now its successful. Thanks for your time  .Its help me a lot .

We can close this issues .

Have a nice day !!

Thanks,
Arun
